// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPyBTNFTayCLMtop_CUI8JllE0aCZ6XSI',
    appId: '1:30052697883:web:39208ded97cb8b90cbf5be',
    messagingSenderId: '30052697883',
    projectId: 'apex-task-69f9e',
    authDomain: 'apex-task-69f9e.firebaseapp.com',
    databaseURL: 'https://apex-task-69f9e-default-rtdb.firebaseio.com',
    storageBucket: 'apex-task-69f9e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5lLW82ijIyVQN_6DijSvpL_UAFevcFfc',
    appId: '1:30052697883:android:7f3230ae73c3255fcbf5be',
    messagingSenderId: '30052697883',
    projectId: 'apex-task-69f9e',
    databaseURL: 'https://apex-task-69f9e-default-rtdb.firebaseio.com',
    storageBucket: 'apex-task-69f9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM8OTqriGyRC-_q27Z-6c9AzFy90V1zpo',
    appId: '1:30052697883:ios:500c51cdaf72694fcbf5be',
    messagingSenderId: '30052697883',
    projectId: 'apex-task-69f9e',
    databaseURL: 'https://apex-task-69f9e-default-rtdb.firebaseio.com',
    storageBucket: 'apex-task-69f9e.firebasestorage.app',
    iosBundleId: 'com.example.apexplanetTask',
  );

}